[module]
  [module.hugoVersion]
    min = "0.81.0"

  [[module.imports]]
    path = "fusejs"
  [[module.imports.mounts]]
    source = 'dist/fuse.min.js'
    target = 'assets/js/libs/fuse.min.js'

  [[module.imports]]
    path = "markjs"
  [[module.imports.mounts]]
    source = 'dist/mark.min.js'
    target = 'assets/js/libs/mark.min.js'
